using System;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WanderingTrader.Core;

namespace WanderingTrader.Infrastructure;

public static class Extensions
{
    public static EntityTypeBuilder<TEntity> HasAutogeneratedKey<TEntity>(this EntityTypeBuilder<TEntity> entityBuilder)
        where TEntity : class, IDbEntity
    {
        entityBuilder.HasKey(x => x.Id);
        entityBuilder.Property(x => x.Id)
          .ValueGeneratedOnAdd();

        return entityBuilder;
    }
}